version: "3"

services:
  frontendmasha:
    restart: unless-stopped
    image: zooyraa/uek_extended_frontend:latest
    container_name: mfrontend
    depends_on:
      - backendmasha
    ports:
      - "8014:80"

  backendmasha:
    restart: unless-stopped
    image: zooyraa/uek_extended_backend:latest
    container_name: mbackend

  redismasha:
    image: redis
    restart: unless-stopped
    ports:
      - 6379

  postgresmasha:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432
    volumes:
      - db_postgres_masha:/var/lib/postgresql/data

  gorsemasha:
    image: zhenghaoz/gorse-in-one
    restart: unless-stopped
    ports:
      - 8086   # gRPC port
      - 8088   # HTTP port
    environment:
      # Use Redis as cache storage backend.
      GORSE_CACHE_STORE: redis://redisMasha:6379
      # Use MySQL as data storage backend.
      GORSE_DATA_STORE: postgres://postgresMasha:postgres@postgres:5432/postgres?sslmode=disable
    command: >
      -c /etc/gorse/config.toml 
      --log-path /var/log/gorse/master.log 
      --cache-path /var/lib/gorse/master_cache.data
    volumes:
      # Mount the configuration file.
      - ./config.toml:/etc/gorse/config.toml
    depends_on:
      - redismasha
      - postgresmasha

volumes:
    db_postgres_masha:
      driver: local