# Your workflow name.
name: Deploy to production.

# Run workflow on every push to main or dev branch.
on:
  push:
    branches: [master, dev]

# Your workflows jobs.
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: echo ${{ secrets.MY_SECRET }}
      - name: SonarQube
        run: ../gradlew sonarqube --info -Dsonar.projectKey=uk223   -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}  -Dsonar.login=${{ secrets.SONAR_TOKEN }}

